# Generated by Django 5.0.6 on 2024-08-13 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_creditcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
