# Generated by Django 5.0.6 on 2024-08-14 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_ticket_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('CONFERENCE', 'Conference'), ('SEMINAR', 'Seminar'), ('MEETING', 'Meeting'), ('WORKSHOP', 'Workshop'), ('CONCERT', 'Concert'), ('FESTIVAL', 'Festival'), ('WEBINAR', 'Webinar'), ('NETWORKING', 'Networking Event'), ('EXHIBITION', 'Exhibition'), ('PARTY', 'Party')], default='CONFERENCE', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
