# Generated by Django 5.0.6 on 2024-08-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_is_approved_event_is_checked_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_checked',
            new_name='is_approved',
        ),
    ]
