# Generated by Django 5.0.6 on 2024-08-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_rename_is_checked_event_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_approved',
            new_name='checked',
        ),
    ]
